### PR TITLE
Fixed CSS Opacity in Internet Explorer

### LINKED ISSUE #121: CSS Opacity and Internet Explorer
Setting opacity to `0` does not work in IE 8 and older, however `"0"` does work. And setting it to `null` or `""` does not work in IE 9 and older.

Also when setting the opacity through the IE Developer Tools console starts using the `filter` property in IE 9, and doesn't work at all in IE 10.

### PR DESCRIPTION
**Pull request by aliebuck**
This should fix #121.

### CODE REVIEW

File: bonzo.js [hunk 1]
```diff
@@ -792,11 +792,15 @@
           iter[o] = opt_v
         }
 
-        if (ie && iter.opacity) {
-          // oh this 'ol gamut
-          iter.filter = 'alpha(opacity=' + (iter.opacity * 100) + ')'
-          // give it layout
-          iter.zoom = o.zoom || 1;
+        if (!features.opasity && 'opacity' in iter) {
+          if (null === iter.opacity || '' === iter.opacity) {
```
Comment (rvagg) [inline bonzo.js]: probably best to turn this into a ternary on `iter.filter = ... ? .. : ..` because the `zoom` below is likely required for both situations

use `===` only when absolutely necessary, prefer a simple `==` in this situation. Also, remove the semicolons from the new code (I know there's one in the original code but it shouldn't be there)

**Comment by rvagg** [comment]
looking good, could you also have a go at adding some basic tests for this? it's tricky to test the actual opacity but could you add at least a test for setting opacity to 0 and then getting the value and making sure it's 0, same for 1.

**Comment by aliebuck** [comment]
Just read the Contributing part of the readme and realised I was doing it wrong :sweat_smile:. 
Updated the correct files and added tests.

**Comment by rvagg** [comment]
Fantastic @jacobbuck, I'll try and get this verified on my end and a release out asap. Ping me here if you don't see any action within a couple of days!

**Comment by aliebuck** [comment]
Hey @rvagg, just checking up on this pull request.

**Comment by rvagg** [comment]
fyi I'm not totally ignoring this, thanks for reminding me, I just need to get to my computer that has my raft of virtual machines on it for testing and then I'll get it out! stay tuned.

**Comment by rvagg** [comment]
:thumbsup: very sorry for the delay, finally back at my desktop where I have my stable of VMs.

released as @1.3.6

**Comment by ded** [comment]
thanks @rvagg
